greeting:
  message: "hello"
quarkus:
  hibernate-orm:
    database:
      generation: "drop-and-create"
  application:
    name: quarkus
  http:
    port: 8083


mp:
  messaging:
    outgoing:
      movies-out:
        topic: "movies"
        connector: "smallrye-kafka"
        key:
          serializer: "org.apache.kafka.common.serialization.IntegerSerializer"
        value:
          serializer: "org.apache.kafka.common.serialization.StringSerializer"
    incoming:
      movies-in:
        topic: "movies"
        connector: "smallrye-kafka"
        key:
          serializer: "org.apache.kafka.common.serialization.IntegerSerializer"
        value:
          serializer: "org.apache.kafka.common.serialization.StringSerializer"

kafka:
  bootstrap:
    servers: "localhost:9092"